### ISSUE TITLE
Problem trying to use with gdrive

### ISSUE THREAD

**Issue by deadc** [riotkit-org/volume-syncing-controller#36]
First of all, nice project!

Im trying to use volume-syncing-controller with google drive type, but im getting error with token value.

```
PodFilesystemSync.yaml:
...
    env:
        REMOTE_TYPE: drive
        REMOTE_CLIENT_ID: xxx.apps.googleusercontent.com
        REMOTE_CLIENT_SECRET: GOCSPX-xxx
        REMOTE_TOKEN: '{"access_token":"xxx","token_type":"Bearer","refresh_token":"xxx","expiry":"2022-05-23T01:04:59.737000688Z"}'
        REMOTE_SCOPE: drive
...
```

And the output:

```
> kubectl logs -n internal -c volume-syncing-sidecar vaultwarden-59f586c868-zm7qk
Error: invalid argument "token = {\"access_token\":\"xxx\",\"token_type\":\"Bearer\",\"refresh_token\":\"xxx\",\"expiry\":\"2022-05-23T01:04:59.737000688Z\"}" for "-p, --param" flag: parse error on line 1, column 10: bare " in non-quoted-field
Usage:
  volume-syncing-controller sync-to-remote [flags]
  ....
```

Not sure if this a problem with rclone itself or volume-syncing-controller

**Comment by blackandred** [comment]
Hi,

Thanks for the feedback, at first - volume-syncing-controller wasn't tested with Google Drive, but it should work if rclone supports it.

Could you please paste a full Pod yaml there? I'm curious what are the parameters set inside the image, maybe there is an escaping issue somewhere.

**Comment by blackandred** [comment]
Ok, I have reproduced the issue - simply by exporting those environment variables in the shell and running outside Kubernetes (volume-syncing-controller can work without Kubernetes).

```
export REMOTE_TYPE=drive
export REMOTE_CLIENT_ID=xxx.apps.googleusercontent.com
export REMOTE_CLIENT_SECRET=GOCSPX-xxx
export REMOTE_TOKEN='{"access_token":"xxx","token_type":"Bearer","refresh_token":"xxx","expiry":"2022-05-23T01:04:59.737000688Z"}'
export REMOTE_SCOPE=drive

make build
./.build/volume-syncing-controller sync-to-remote
```

```
Error: invalid argument "token = {\"access_token\":\"xxx\",\"token_type\":\"Bearer\",\"refresh_token\":\"xxx\",\"expiry\":\"2022-05-23T01:04:59.737000688Z\"}" for "-p, --param" flag: parse error on line 1, column 10: bare " in non-quoted-field
```

**Comment by blackandred** [comment]
Related issues in other OSS projects:
https://github.com/open-policy-agent/opa/pull/2421
https://github.com/containers/podman/pull/2582

**Comment by blackandred** [comment]
Its working for me initially - I will try to connect some Google Drive account to perform a complete test.

```
./.build/volume-syncing-controller sync-to-remote -v   
INFO[0000] Performing copy from './' to 'remote:/'      
2022/11/26 15:04:44 DEBUG : Setting --config "rclone.conf" from environment variable RCLONE_CONFIG="rclone.conf"
2022/11/26 15:04:44 DEBUG : rclone: Version "1.60.0" starting with parameters ["rclone" "copy" "--create-empty-src-dirs" "./" "remote:/" "-vv"]
2022/11/26 15:04:44 DEBUG : Creating backend with remote "./"
2022/11/26 15:04:44 DEBUG : Using config file from "/home/user/GolandProjects/volume-syncing-controller/rclone.conf"
2022/11/26 15:04:44 DEBUG : fs cache: renaming cache item "./" to be canonical "/home/user/GolandProjects/volume-syncing-controller"
2022/11/26 15:04:44 DEBUG : Creating backend with remote "remote:/"
2022/11/26 15:04:44 DEBUG : remote: Loaded invalid token from config file - ignoring
2022/11/26 15:04:44 DEBUG : remote: Token refresh failed try 1/5: oauth2: cannot fetch token: 401 Unauthorized
Response: {
  "error": "invalid_client",
  "error_description": "The OAuth client was not found."
}
```

**Comment by blackandred** [comment]
I will leave this up to you to test it. I'm merging the PR and tagging a next RC release, in case there will be some issue with Google Drive itself, but not related to escaping please create a separate issue. In this issue please let me know if the escaping issue is still valid.

**Comment by deadc** [comment]
Hey!

Thanks for the quick response, I performed new tests and related to double quotes it's working normally now, thanks!

Another problem related to communication with the google api appeared, I opened a [PR](https://github.com/riotkit-org/volume-syncing-controller/pull/39) correcting it.

I believe we can close this issue.

**Comment by deadc** [comment]
Sorry!

I've found the same problem with double quotes using initContainer.

```
> kubectl logs -n internal vaultwarden-7cbc67d789-g65bw -c init-volume-restore
Error: invalid argument "token={\"access_token\":\"xxx\",\"token_type\":\"Bearer\",\"refresh_token\":\"xxx\",\"expiry\":\"2022-11-26T23:48:47.50611305-03:00\"}" for "-p, --param" flag: parse error on line 1, column 8: bare " in non-quoted-field
Usage:
  volume-syncing-controller remote-to-local-sync [flags]
```

edit: I took the liberty of opening another PR correcting the problem.
- https://github.com/riotkit-org/volume-syncing-controller/pull/40

**Comment by blackandred** [comment]
I have reviewed and merged your PRs, then tagged a new release after tests passed - `v1.0.1-rc1`

btw. I hope there will be a non-rc release till the end of the year 😄

**Comment by blackandred** [comment]
Please let me know if I could close the issue, or close the issue if you are able to.

**Comment by deadc** [comment]
All components seem to be working now. thanks!!
